### ISSUE TITLE
Making taskID in AsyncResult a public field.

### ISSUE THREAD

**Issue by danielchengml** [gocelery/gocelery#104]
https://github.com/gocelery/gocelery/blob/892a6d55c1d7e9aa51a1b613f68e600c6f6a6ffb/gocelery.go#L113

Hi @sickyoon, great project you have done! I was wondering what the reason was for setting the fields in `AsyncResult` as private fields especially `taskID`. I am hoping to retrieve the TaskID immediately after I submit the task to the queue even before the queue's been worked on by the worker. Would it be possible to change it to a public field? eg.
```
type AsyncResult struct {
	TaskID  string
	backend CeleryBackend
	result  *ResultMessage
}
```

**Comment by sickyoon** [comment]
Hey @danielchengml I don't see a problem with making `TaskID` public.
Why don't you create a PR?

**Comment by danielchengml** [comment]
Thanks for your prompt reply @sickyoon! Made a PR ^

**Comment by sickyoon** [comment]
PR merged.
