### ISSUE TITLE
Creating an interface for CeleryClient

### ISSUE THREAD

**Issue by danielchengml** [gocelery/gocelery#106]
https://github.com/gocelery/gocelery/blob/892a6d55c1d7e9aa51a1b613f68e600c6f6a6ffb/gocelery.go#L14

Thoughts on creating an `interface` for `type CeleryClient struct`? The interface would look something like this:

```
// Client Inferface defines the methods we use for the Client
type Client interface {
	Register(name string, task interface{})
	StartWorkerWithContext(ctx context.Context)
	StartWorker()
	StopWorker()
	WaitForStopWorker()
	Delay(task string, args ...interface{}) (*AsyncResult, error)
	DelayKwargs(task string, args map[string]interface{}) (*AsyncResult, error)
}
```

This thought came about as I was mocking `CeleryClient` for testing purposes. However, it is also possible to include this interface in the user/consumer's repo together with the mocks.

**Comment by sickyoon** [comment]
I think this can easily be achieved in your own code. Also it might be better idea to mock broker/backend instead.
