### ISSUE TITLE
Monitoring Tool/UI for Gocelery (FlowerUI)

### ISSUE THREAD

**Issue by danielchengml** [gocelery/gocelery#107]
Hi @sickyoon would you know if there is any Monitoring UI for gocelery just like how Flower UI can monitor celery? Or do you know if flower UI can be configured to server a gocelery application?

**Comment by sickyoon** [comment]
I haven't tried myself but I suppose it should be compatible.

**Comment by danielchengml** [comment]
@sickyoon I've looked into the compatibility of [mher/flower](github.com/mher/flower) and gocelery and realized that they are incompatible. So while flower was built to monitor python celery and gocelery and celery share the same protocol, the method in which flower monitors celery doesn't work for gocelery. 

It seems like flower is able to communicate directly with python celery's worker and instrument the tasks accordingly. How flow communicates is via inheriting a `celery` method called [`EventReceiver()`](https://github.com/mher/flower/blob/ceb6e1bd8c432f7783ef6345485d1abd6c7f492b/flower/events.py#L19). This method allows flower to receive events from worker including tasks completed or failed.

Additionally, the `EventReceiver()` method uses [celery/kombu](https://github.com/celery/celery/blob/9f0a554dc2d28c630caf9d192873d040043b7346/celery/events/receiver.py#L7) as a messaging library. Kombu is currently written in python.

Therefore, it seems like Flower UI isn't directly compatible and in order to monitor gocelery tasks, we would need a Go specific tool.

**Comment by sickyoon** [comment]
@danielchengml that can be interesting project: reverse-engineering kombu and build go client.
I have been busy lately. I'll look once I have time.

**Comment by danielchengml** [comment]
@sickyoon Yeah, definitely an interesting project right there. Another one that would be interesting could be a Go written monitoring tool for gocelery with or without kombu. Will be keen to chat more when you have the time to look at this.

**Comment by pghook** [comment]
Looking forward to this feature @yoonsio
