### ISSUE TITLE
Update gocelery to use Go 1.13 and Go modules

### ISSUE THREAD

**Issue by martincapello** [gocelery/gocelery#132]
Hi, I was wondering if there is any interest in supporting the latest Go version (1.13 at the moment of writing) and replace dep by Go modules.
So, I already made a PR https://github.com/gocelery/gocelery/pull/131 for this :slightly_smiling_face: 

Now, I'm trying to figure out why code coverage has decreased...since I didn't touch the source code :thinking:

**Comment by sickyoon** [comment]
PR merged.
