### ISSUE TITLE
How does gocelery "pick off" tasks from Redis?

### ISSUE THREAD

**Issue by aaronn** [gocelery/gocelery#138]
I'm using `gocelery` in production and we're hitting a point where tasks are constantly running. Unfortunately, it seems like we've recently hit a stumble where we had a bunch of downtime and as a result a bunch of tasks piled up. Upon restarting `gocelery` these tasks are queued up and about a day behind.

How exactly does gocelery pull tasks from redis, and is there any way for me to purge this backlog?

**Comment by sickyoon** [comment]
Hey, @aaronn I am glad to hear that you are trying out gocelery in your production environment. I'd love to jump on a call to discuss any challenges you may have.

To answer your question, GoCelery uses `BRPOP` command but this answer is likely irrelevant to your issue. Celery uses `expires` flag to invalidate old tasks independent of a broker. However, GoCelery does not yet support `expires` flag. I created a new issue to fix this: https://github.com/gocelery/gocelery/issues/141

**Comment by sickyoon** [comment]
@aaronn `expires` flag is now supported: https://github.com/gocelery/gocelery/pull/146
Let me know if you have any more issues.
