### ISSUE TITLE
Postgresql as broker

### ISSUE THREAD

**Issue by gadelkareem** [gocelery/gocelery#153]
Any plans to add PostgreSQL to list of brokers?

**Comment by sickyoon** [comment]
I can support it if there is a demand. It would be helpful if you could share your use cases.

**Comment by gadelkareem** [comment]
So I need to add a queue system to https://gitlab.com/gadelkareem/skeleton . And since I am deploying the demo to Heroku free tier, PostgreSQL is the easiest way to manage the queue. Moreover using database for queueing is very common in many frameworks ex https://laravel.com/docs/7.x/queues

There are a lot of advantages for using PostgreSQL, ex https://gist.github.com/chanks/7585810 , and there is a port for ruby gem to Golang here https://github.com/bgentry/que-go

**Comment by sickyoon** [comment]
It looks like it is not officially supported by the Celery project. https://github.com/celery/celery/issues/5149 
I don't think free tier availability is a good reason to support entire new broker/backend.

**Comment by bbkgh** [comment]
> I can support it if there is a demand. It would be helpful if you could share your use cases.

Hi. We have another use case. We have multi-zone database (CockrochDB) that is wire compatible with Postgresql. It would be nice to use postgres as broker for deploying multi zone/datacenter celery worker that are synced by backend broker. With this we can achieve symmetric deployments on multi datacenter.

Is there any other solution for synchronizing workers? like using cockroachdb as lock management system and try to obtain a lock before every task?  i don't know how can i prevent to run tasks in not leader cluster. Is there any workaround for running a function before every task (like prerun hook) and don't run main task if this function fails?

**Comment by alexign** [comment]
@bbkgh just use routing https://docs.celeryproject.org/en/stable/userguide/routing.html#manual-routing
So you can route your task to leader cluster
Also you can always raise an exception it task and handle it to make celery task failed in controllable way

**Comment by MattOates** [comment]
> We have multi-zone database (CockrochDB) that is wire compatible with Postgresql.

Worth pointing out on here that CockroachDB don't support NOTIFY/(UN)LISTEN https://github.com/cockroachdb/cockroach/issues/41522 but they are considering it from user requests.
