### ISSUE TITLE
Race-condition with worker task execution

### ISSUE THREAD

**Issue by keon94** [gocelery/gocelery#173]
Hello,

This [logic](https://github.com/gocelery/gocelery/blob/825d89059344006c104412e628d456b3a111a6a5/worker.go#L140) in the worker is not thread safe. When the client registers a function with a Task interface instance, that task is essentially a singleton bound to that function-name that will be shared between all worker threads accessing it during execution. As a result, calls to ParseKwargs and making variable assignments on the instance will be dangerous as it'll lead to nondeterministic behavior if multiple threads are concurrently running that task from different calls.

Without backwards compatibility in mind, the cleanest solution to this would be to rework the CeleryTask interface to simply have a single method with signature _RunTask(kwargs map[string]interface{}) (interface{}, error)_ which will do ParseKwargs and RunTask in one shot. This way we'd restrict the burden of state management to the method's scope.

That however may not be feasible as that'll break existing client code. Nonetheless, this is a serious issue that I have confirmed during testing.

**Comment by DriedYellowPeach** [comment]
Did you mean this?
```go
if ok {
		if err := taskInterface.ParseKwargs(message.Kwargs); err != nil {
			return nil, err
		}
		val, err := taskInterface.RunTask()
		if err != nil {
			return nil, err
		}
		return getResultMessage(val), err
	}

```
this  ParseKwargs write some struct fields and this taskInterface will be accessed by several goroutines(workers). But actually, this taskInterface is not a **shared variable**

beacause this line, in the same function:
```go
taskInterface, ok := task.(CeleryTask)
```
this type assertion will create a new variable, so every goroutine will use a copy of the original task, there is no shared variable.

**Comment by keon94** [comment]
@DriedYellowPeach Good catch. Still, that's a shallow copy, so basically any pointer fields will end up being shared (which is what my original test must have been using). The developers will just have to keep in mind not to change state on such fields (or do so with mutexes, etc), or not include them altogether. That said, this is not really an issue, but maybe it could be documented better.
