### ISSUE TITLE
Please do NOT rewrite git history

### ISSUE THREAD

**Issue by kostrahb** [gocelery/gocelery#55]
I had quite old version of gocelery from february and today I have updated it with `go get -u all`. After executing this command I got error message:

```
From https://github.com/gocelery/gocelery
 + 7e28cee...b2f0dd7 master     -> origin/master  (forced update)
fatal: refusing to merge unrelated histories
package github.com/gocelery/gocelery: exit status 128
```

Please do not rewrite git history in public repositories, it causes unnecessary troubles!

![history](https://user-images.githubusercontent.com/8557957/44453667-ec9dbb80-a5f9-11e8-8604-965bb0ae1122.png)

**Comment by sickyoon** [comment]
duly noted
